import Url from './Url';
import Attribute from './Attribute';
import Metadata from './Metadata';
import Phone from './Phone';
import Schedule from './Schedule';
import ServiceArea from './ServiceArea';
import ServiceAtLocation from './ServiceAtLocation';
import Language from './Language';
import Funding from './Funding';
import CostOption from './CostOption';
import Program from './Program';
import RequiredDocument from './RequiredDocument';
import Contact from './Contact';
import ServiceCapacity from './ServiceCapacity';
import Organization from './Organization';

export interface Service {
  id: string;
  name: string;
  alternate_name: string | null;
  description: string | null;
  url: string | null;
  additional_urls: Url[] | null;
  email: string | null;
  status: string;
  interpretation_services: string | null;
  application_process: string | null;
  fees_description: string | null;
  accreditations: string | null;
  eligibility_description: string | null;
  minimum_age: number | null;
  maximum_age: number | null;
  assured_date: string | null;
  assurer_email: string | null;
  alert: string | null;
  last_modified: string | null;
  phones: Phone[] | null;
  schedules: Schedule[] | null;
  service_areas: ServiceArea[] | null;
  service_at_locations: ServiceAtLocation[] | null;
  languages: Language[] | null;
  organization: Organization | null;
  funding: Funding[] | null;
  cost_options: CostOption[] | null;
  program: Program | null;
  required_documents: RequiredDocument[] | null;
  contacts: Contact[] | null;
  capacities: ServiceCapacity[] | null;
  attributes: Attribute[] | null;
  metadata: Metadata[] | null;
}
