import Url from './Url';
import Attribute from './Attribute';
import Metadata from './Metadata';
import Phone from './Phone';
import Schedule from './Schedule';
import ServiceArea from './ServiceArea';
import ServiceAtLocation from './ServiceAtLocation';
import Language from './Language';
import Funding from './Funding';
import CostOption from './CostOption';
import Program from './Program';
import RequiredDocument from './RequiredDocument';
import Contact from './Contact';
import ServiceCapacity from './ServiceCapacity';
import Organization from './Organization';

export interface Service {
  id: string;
  name: string;
  alternateName: string;
  description: string;
  url: string;
  additionalUrls: Url[];
  email: string;
  status: string;
  interpretationServices: string;
  applicationProcess: string;
  feesDescription: string;
  waitTime: string;
  fees: string;
  accreditations: string;
  eligibilityDescription: string;
  minimumAge: number;
  maximumAge: number;
  assuredDate: string;
  assurerEmail: string;
  licenses: string;
  alert: string;
  lastModified: string;
  phones: Phone[];
  schedules: Schedule[];
  serviceAreas: ServiceArea[];
  serviceAtLocations: ServiceAtLocation[];
  languages: Language[];
  organization: Organization;
  funding: Funding[];
  costOptions: CostOption[];
  program: Program | null;
  requiredDocuments: RequiredDocument[];
  contacts: Contact[];
  capacities: ServiceCapacity[];
  attributes: Attribute[];
  metadata: Metadata[];
}
