import Url from './Url';
import Attribute from './Attribute';
import Metadata from './Metadata';
import Phone from './Phone';
import Schedule from './Schedule';
import ServiceArea from './ServiceArea';
import ServiceAtLocation from './ServiceAtLocation';
import Language from './Language';
import Funding from './Funding';
import CostOption from './CostOption';
import Program from './Program';
import RequiredDocument from './RequiredDocument';
import Contact from './Contact';
import ServiceCapacity from './ServiceCapacity';
import Organization from './Organization';

export interface Service {
  id: string;
  name: string;
  alternate_name?: string;
  description?: string;
  url?: string;
  additional_urls?: Url[];
  email?: string;
  status: string;
  interpretation_services?: string;
  application_process?: string;
  fees_description?: string;
  accreditations?: string;
  eligibility_description?: string;
  minimum_age?: number;
  maximum_age?: number;
  assured_date?: string;
  assurer_email?: string;
  alert?: string;
  last_modified?: string;
  phones?: Phone[];
  schedules?: Schedule[];
  service_areas?: ServiceArea[];
  service_at_locations?: ServiceAtLocation[];
  languages?: Language[];
  organization?: Organization;
  funding?: Funding[];
  cost_options?: CostOption[];
  program?: Program;
  required_documents?: RequiredDocument[];
  contacts?: Contact[];
  capacities?: ServiceCapacity[];
  attributes?: Attribute[];
  metadata?: Metadata[];
}
